### ISSUE TITLE
Problem converting Ruby snippets file from `honza/vim-snippets`

### ISSUE THREAD

**Issue by andyw8** [VincentCordobes/convert-snippets#16]
Hi, thanks for building this library.

Just wanted to report a problem when trying to convert this snippet file:

https://github.com/honza/vim-snippets/blob/master/UltiSnips/ruby.snippets

The output is an empty hash `{}`. No errors are reported.

This other file in the same repo seems to convert fine:

https://github.com/honza/vim-snippets/blob/master/UltiSnips/rails.snippets

Thanks
Andy

**Comment by VincentCordobes** [comment]
Hi, I can't reproduce. Do you have the latest version ?

**Comment by andyw8** [comment]
Thanks, I tried again and it worked. Not sure what I was doing wrong previously.
